Feat/added security context
Improwised/charts pull request #38
Opened 2023-06-14 12:35 UTC by Hussain-Gandhi

## Fixes Issue
Closes #37 

## Changes proposed
Added the following fields in job, cronjob, service, and worker templates.

    securityContext:
      fsGroup: <value>
      runAsGroup: <value>
      runAsUser: <value>

## Check List
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-06-14 12:36 UTC, Bhoomiz01 approved these changes

2023-06-14 12:42 UTC, ankitjilka approved these changes

2023-06-14 12:43 UTC, lalitmoza approved these changes

2023-06-14 13:34 UTC, deltasquare4 requested changes
SecurityContext value is only picked up from individual objects, but not from their template. It also doesn't have a default. I think this is better implemented like `resources` - using `with` statement.

2023-06-15 10:13 UTC, deltasquare4 approved these changes

2023-06-15 10:16 UTC, merged